sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t eyehwan/docker-react -f Dockerfile.dev . 

script:
  - docker run eyehwan/docker-react npm run test -- --coverage